# Header
menu:
  Documentation: https://docs.microsoft.com/en-us/adaptive-cards/
  Schema Explorer: /explorer/AdaptiveCard.html
  Visualizer: /visualizer
  Samples: /samples/ActivityUpdate.html
  Connect: /connect
  
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
#sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /content/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
