# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: pic2card-build
on:
  push:
    branches: [ master, main, 'pic2card-backend/**' ]
    paths:
    - 'source/pic2card/**'
  pull_request:
    branches: [ master, main, 'pic2card-backend/**' ]
    paths:
    - 'source/pic2card/**'
defaults:
  run:
    shell: bash
    working-directory: source/pic2card
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libsm6 tesseract-ocr
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        
        python -m pip install --upgrade pip
        pip install pytest pylint==2.9.3 black
        if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi
        if [ -f requirements/requirements-frozen_graph.txt ]; then pip install -r requirements/requirements-frozen_graph.txt; fi        
        if [ -f requirements/requirements-dev.txt ]; then pip install -r requirements/requirements-dev.txt; fi
   
    - name: Lint with pylint and Black
      run: |
        find . -type f -name "*.py" | xargs pylint
        black --check --line-length 80 .
    - name: Test with pytest
      run: |
        pytest
