# This workflow will install npm dependencies and run tests
name: react-native-build

on:
  push:
    branches: [ reactnative/release-2.2-tests ]
    paths:
    - 'source/community/reactnative/**'
  pull_request:
    branches: [ reactnative/release-2.2 ]
    paths:
    - 'source/community/reactnative/**'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      working-directory: ./source/community/reactnative
      run: npm install
    - name: Run test
      working-directory: ./source/community/reactnative
      run: npm test